branches:
  only:
    - master

language: ruby
rvm:
  - "2.7.0"

script: 
  - bundle exec rspec spec
  # - CODECLIMATE_REPO_TOKEN=${CODECLIMATE_LAB42CORE_TOKEN} bundle exec codeclimate-test-reporter

